# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# OpenGraph / Twitter metadata
title: .gov TLD
description: .gov is the top-level domain for US-based government organizations.

# GA and GitHub data
google_analytics_ua: ua-33523145-2
repo: https://github.com/cisagov/dotgov-home

search_site_handle: dotgov

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

styles:
  - /assets/css/main.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/

kramdown:
  parse_block_html: true
