title: DotGov
description: Home of the DotGov program, which operates the .gov DNS registry and zone.
logo:
repo: https://github.com/GSA/dotgov-home
google_analytics_ua: UA-99995535-1

# Site Status
banner: A website of the United States Government
phase: Production # alpha, beta, live

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

sass:
  style: :compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/
