# Using https://github.com/18F/uswds-jekyll
theme: uswds-jekyll

# OpenGraph / Twitter metadata
title: DotGov
description: Home of the DotGov program, which operates the .gov DNS registry and zone.

# GA and GitHub data
google_analytics_ua: UA-99995535-1
repo: https://github.com/GSA/dotgov-home

exclude:
- CONTRIBUTING.md
- _config.yml
- .travis.yml
- .gitignore
- Gemfile
- Gemfile.lock
- LICENSE.md
- README.md
- vendor

styles:
  - /assets/uswds/css/uswds.min.css
  - /assets/uswds-overrides.css

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

collections:
  pages:
    output: true
    #permalink: /:path/

